[package]
name = "advent_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
nom = "8.0"
regex = "1"
num = "0.4"
itertools = "0.12.0"